### ISSUE TITLE
Bug uploading picture into alert

### ISSUE THREAD

**Issue by priamai** [StrangeBeeCorp/TheHive-feedback#5]
### Request Type
Bug

### Work Environment

| Question                   | Answer                                |
| -------------------------- | ------------------------------------- |
| OS version (server)        | Ubuntu  |
| OS version (client)        | Windows |
| Virtualized  Env.          | False                          |
| Dedicated RAM              | 32 GB                                 |
| vCPU                       |  8       |
| TheHive version            | 5.x.x                                 |
| Package Type               | Docker |
| Database                   | Builtin               |
| Index type                 | Builtin              |
| Attachments storage        | Local           |
| Browser type & version     | Chrome         |

### Problem Description
In an incident I try to upload an image.
Nothing happens and lot of red errors in the browser console.

### Steps to Reproduce
1. Create a case from an alert
2. Go to Pages
3. Create a Page
4. Add an image

### Complementary information

![image](https://user-images.githubusercontent.com/57333254/171562339-4eca3a44-3fdb-4425-802f-12a42f294649.png)

My docker setup:

```
version: "3"
services:
  thehive:
    image: strangebee/thehive:latest
    mem_limit: 1500m
    user: root
    ports:
      - "9000:9000"
    environment:
      - JVM_OPTS="-Xms1024M -Xmx1024M"
    command:
      - --secret
      - "victoriasecret2022!"
      - "--no-config-cortex"
    volumes:
      - thehive_db:/data/db
      - thehive_files:/data/files
      - thehive_index:/data/index
volumes:
  thehive_db:
  thehive_files:
  thehive_index:

```
